### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DisplayedAim** [vannaka/Motion_Profile_Generator#33]
I continue to get this error in a popup when I run the gradle program.
java.io.FileNotFoundException: File /pathfinderjava.dll was not found inside JAR.
	at com.mammen.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:105)
	at com.mammen.ui.javafx.MainUIController.initialize(MainUIController.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
	at com.mammen.main.Main.start(Main.java:20)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by blake1029384756** [comment]
This happens when you try to build with gradle or when you run the app after its built?

**Comment by DisplayedAim** [comment]
This is happening when I try to build with gradle, it comes as a pop up. If I close it, the application still works but doesn't function as expected.

**Comment by vannaka** [comment]
Sounds like it building without the dll. And then running the app. Is the dll in your Project?

**Comment by blake1029384756** [comment]
What vannaka makes sense. I just built the app just fine.

**Comment by DisplayedAim** [comment]
vannaka I checked it, it seems to be in the folder.

**Comment by DisplayedAim** [comment]
in the lib/native_libs DIR

**Comment by vannaka** [comment]
What os are you on? Is it 32 or 64 bit?

**Comment by blake1029384756** [comment]
I removed the dll before I built the app and got the exact same error. Yes the app opens but you arent able to generate a path.
![Imgur](https://i.imgur.com/MjgCCDS.jpg)

**Comment by DisplayedAim** [comment]
So what am I supposed to do then?

**Comment by blake1029384756** [comment]
can you please clone the repo and try again?

**Comment by vannaka** [comment]
What's your os details?

**Comment by DisplayedAim** [comment]
I've tried and it works now, however I have another little problem.

**Comment by DisplayedAim** [comment]
I'll post a ss, it's probably something simple to fix however I'm not too intelligent

**Comment by DisplayedAim** [comment]
Well the file & help bar options aren't appearing and I'm not sure why :/ 
![capture](https://user-images.githubusercontent.com/33333386/42982641-9012015c-8c25-11e8-951e-d8efa7da039f.PNG)

**Comment by DisplayedAim** [comment]
btw its Windows 10

**Comment by vannaka** [comment]
Ohhhhh that's weird. I've never seen that before. Give us a bit of time to research and we'll see what we can figure out.

**Comment by Team1718** [comment]
I'm seeing the same issue.  I've just installed the eclipse IDE and buildship (the gradle - eclipse integration).  When I import it using buildship and attempt to run it I get this error.

When I try to run it in eclipse without using the gradle integration, I get the same error.

Note:  I am completely new to both eclipse and java programming.

**Comment by Team1718** [comment]
No problem - thanks for the quick response.  I just re-downloaded the project and used the gradle build commands.  When I ran the created jar file I'm getting the same response - the FRC field is not viewable.

**Comment by DisplayedAim** [comment]
I'm guessing you still have to import the field into the workspace, go [File, Settings] then import the image from the directory folder that you installed. The field workspace should be located in the images folder and it should automatically appear. @vannaka I'm still having issues getting the top bar to appear, maybe it's an issue w/ getting the right screen size.

**Comment by blake1029384756** [comment]
@DisplayedAim  and @Team1718 Your issues have been moved to their respective issues. Window issue #35 and run error in eclipse #36
